export * from './WaveText/WaveTextAnimator'
export * from './Modal/Modal'
export * from './pages/mainpage/RequestFreeLesson/requestFreeLesson'
export * from './pages/mainpage/Sections/section1Content'
export * from './pages/mainpage/Sections/section2Content'